################################################################################
#   SECTION: Capabilities
################################################################################
Capabilities:
    Channel: &ChannelCapabilities
        V2_0: true
    Orderer: &OrdererCapabilities
        V2_0: true
    Application: &ApplicationCapabilities
        V2_0: true

################################################################################
#   CHANNEL Defaults
################################################################################
Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities

################################################################################
#   Section: Organizations
################################################################################
Organizations:
    - &Orderer
      Name: OrdererMSP
      ID: OrdererMSP
      MSPDir: crypto-config/peerOrganizations/orderer.healthcare.com/msp

      Policies:
          Readers:
              Type: Signature
              Rule: "OR('OrdererMSP.member')"
          Writers:
              Type: Signature
              Rule: "OR('OrdererMSP.member')"
          Admins:
              Type: Signature
              Rule: "OR('OrdererMSP.admin')"
          Endorsement:
              Type: Signature
              Rule: "OR('OrdererMSP.member')"

      AnchorPeers:

    - &patient
      Name: patientMSP
      ID: patientMSP
      MSPDir: crypto-config/peerOrganizations/patient.healthcare.com/msp

      Policies:
          Readers:
              Type: Signature
              Rule: "OR('patientMSP.member')"
          Writers:
              Type: Signature
              Rule: "OR('patientMSP.member')"
          Admins:
              Type: Signature
              Rule: "OR('patientMSP.admin')"
          Endorsement:
              Type: Signature
              Rule: "OR('patientMSP.member')"

      AnchorPeers:
          - Host: peer0.patient.healthcare.com
            Port: 7041

    - &doctor
      Name: doctorMSP
      ID: doctorMSP
      MSPDir: crypto-config/peerOrganizations/doctor.healthcare.com/msp

      Policies:
          Readers:
              Type: Signature
              Rule: "OR('doctorMSP.member')"
          Writers:
              Type: Signature
              Rule: "OR('doctorMSP.member')"
          Admins:
              Type: Signature
              Rule: "OR('doctorMSP.admin')"
          Endorsement:
              Type: Signature
              Rule: "OR('doctorMSP.member')"

      AnchorPeers:
          - Host: peer0.doctor.healthcare.com
            Port: 7061

    - &pharmacy
      Name: pharmacyMSP
      ID: pharmacyMSP
      MSPDir: crypto-config/peerOrganizations/pharmacy.healthcare.com/msp

      Policies:
          Readers:
              Type: Signature
              Rule: "OR('pharmacyMSP.member')"
          Writers:
              Type: Signature
              Rule: "OR('pharmacyMSP.member')"
          Admins:
              Type: Signature
              Rule: "OR('pharmacyMSP.admin')"
          Endorsement:
              Type: Signature
              Rule: "OR('pharmacyMSP.member')"

      AnchorPeers:
          - Host: peer0.pharmacy.healthcare.com
            Port: 7081

    - &lab
      Name: labMSP
      ID: labMSP
      MSPDir: crypto-config/peerOrganizations/lab.healthcare.com/msp

      Policies:
          Readers:
              Type: Signature
              Rule: "OR('labMSP.member')"
          Writers:
              Type: Signature
              Rule: "OR('labMSP.member')"
          Admins:
              Type: Signature
              Rule: "OR('labMSP.admin')"
          Endorsement:
              Type: Signature
              Rule: "OR('labMSP.member')"

      AnchorPeers:
          - Host: peer0.lab.healthcare.com
            Port: 7101

    - &insurance
      Name: insuranceMSP
      ID: insuranceMSP
      MSPDir: crypto-config/peerOrganizations/insurance.healthcare.com/msp

      Policies:
          Readers:
              Type: Signature
              Rule: "OR('insuranceMSP.member')"
          Writers:
              Type: Signature
              Rule: "OR('insuranceMSP.member')"
          Admins:
              Type: Signature
              Rule: "OR('insuranceMSP.admin')"
          Endorsement:
              Type: Signature
              Rule: "OR('insuranceMSP.member')"

      AnchorPeers:
          - Host: peer0.insurance.healthcare.com
            Port: 7121

################################################################################
#   SECTION: Application
################################################################################
Application: &ApplicationDefaults
    Organizations:
    # Policies defines the set of policies at this level of the config tree
    # For Application policies, their canonical path is
    #   /Channel/Application/<PolicyName>
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        Endorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
    Capabilities:
        <<: *ApplicationCapabilities

################################################################################
#   SECTION: Orderer
################################################################################
Orderer: &Group1Defaults
    OrdererType: solo
    Addresses:
        - orderer0.group1.orderer.healthcare.com:7030
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Organizations:
    # Policies defines the set of policies at this level of the config tree
    # For Orderer policies, their canonical path is
    #   /Channel/Orderer/<PolicyName>
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        # BlockValidation specifies what signatures must be included in the block
        # from the orderer for the peer to validate it.
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"
    Capabilities:
        <<: *OrdererCapabilities

################################################################################
#   Profile
################################################################################
# https://github:com/hyperledger/fabric/blob/master/sampleconfig/configtx.yaml

Profiles:
    # Profile used to create Genesis block for group group1 #
    Group1Genesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *Group1Defaults
            Organizations:
                - *Orderer
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *Orderer
                    - *patient
                    - *doctor
                    - *pharmacy
                    - *lab
                    - *insurance

    # Profile used to create channeltx for main-channel1 #
    MainChannel1:
        <<: *ChannelDefaults
        Orderer:
            <<: *Group1Defaults
            Organizations:
                - *Orderer
            Capabilities:
                <<: *ApplicationCapabilities
        Consortium: SampleConsortium
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *patient
                    - *doctor
                    - *pharmacy
                    - *lab
                    - *insurance
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *patient
                - *doctor
                - *pharmacy
                - *lab
                - *insurance
